### PR TITLE
Use exposingList utility function from Elm.Syntax.Module

### PR DESCRIPTION
**Pull request by stil4m**
Less is more :)

### CODE REVIEW

**Comment by mbuscemi** [comment]
Funny how I missed that. I was just looking at that this morning and thinking it could be cleaner. Thanks!

**Comment by stil4m** [comment]
I'm looking to move some functions from elm-analyse into elm-syntax. Turned out I had that function duplicated over the two projects :/.

**Comment by mbuscemi** [comment]
Please let me know if there are any other ways I can optimize my usage of elm-syntax. Also, if any existing Elm Lens code could be turned into more generic behavior for elm-syntax, I'm open to doing those refactors.

**Comment by stil4m** [comment]
Yes I will. I'm preparing a PR for this, but I also require a major version bump on elm-analyse. I want to be sure that I get the most out of that major change.

**Pull request merged**
